tv_shows = [
    ["Narcos", "The story of drug kingpin Pablo Escobar and the DEA agents who hunted him."],
    ["Fleabag", "The life of a dry-witted, sexually-liberated woman living in London."],
    ["Ozark", "A financial advisor is forced to relocate his family to the Ozarks."],
    ["Loki", "The god of mischief travels through time."],
    ["Spartacus", "A Thracian gladiator leads a slave uprising."],
    ["Banshee", "An ex-con assumes the identity of a small-town sheriff."],
    ["Daredevil", "A blind lawyer fights crime in Hell's Kitchen."],
    ["Travelers", "Special agents from the future live undercover in the present."],
    ["Firefly", "A group of rebels on the run in a distant future."],
    ["Salem", "Witches in 17th-century Salem, Massachusetts."],
    ["Dexter", "A serial killer works as a blood-spatter analyst for the Miami police."],
    ["Dark", "A sinister time travel conspiracy between 4 families."]
]

movies = [
    ["Inception", "A thief is given an impossible task by a wealthy businessman."],
    ["Joker", "The origin story of the Joker."],
    ["Spectre", "James Bond is forced to confront his past."],
    ["Gravity", "An astronaut is lost in space."],
    ["Elysium", "A man tries to cross the border into a utopian paradise."],
    ["Interstellar", "A team of astronauts search for a new home for humanity."],
    ["Lucy", "A woman gains superhuman powers after being exposed to a substance."],
    ["Memento", "A man seeks revenge for his wife's murder."],
    ["Unlocked", "A CIA agent is given a mission to stop a terrorist attack."],
    ["Zombieland", "A group of survivors travel across a dystopian America."],
    ["Eagle", "A Roman soldier is sent to Britain to find a lost legion's eagle."],
    ["Fury", "A group of soldiers are sent on a mission."],
    ["Inferno", "A symbologist is forced to go on the run."],
    ["Prometheus", "A group of explorers is sent to the explore the origins of humanity."],
    ["Prey", "A tribal girl tries to hunt a predator to gain more respect."]
]

wordlist = [
    ["apple", "a type of fruit"],
    ["dog", "an animal that is often kept as a pet"],
    ["house", "a place where people live"],
    ["car", "a vehicle with wheels"],
    ["pen", "a writing instrument"],
    ["paper", "a material used for writing"],
    ["pencil", "a writing instrument"],
    ["book", "a collection of pages"],
    ["phone", "a device used for communication"],
    ["music", "an art form with sound"],
    ["movie", "a form of entertainment"],
    ["game", "an activity for fun"],
    ["computer", "a machine for processing information"],
    ["program", "a set of instructions for a computer"],
    ["website", "a place on the internet"],
    ["email", "a message sent through the internet"],
    ["facebook", "a social network"],
    ["google", "a search engine"],
    ["youtube", "a video sharing website"],
    ["twitter", "a social network"],
    ["instagram", "a social network"],
    ["facebook", "a social network"],
    ["apple", "a type of fruit"],
    ["banana", "a type of fruit"],
    ["orange", "a type of fruit"],
    ["grape", "a type of fruit"],
    ["lemon", "a type of fruit"],
    ["mango", "a type of fruit"],
    ["strawberry", "a type of fruit"],
    ["pineapple", "a type of fruit"],
    ["watermelon", "a type of fruit"],
    ["peach", "a type of fruit"],
    ["kiwi", "a type of fruit"],
    ["cherry", "a type of fruit"],
    ["avocado", "a type of fruit"],
    ["pear", "a type of fruit"],
    ["plum", "a type of fruit"],
    ["grapes", "a type of fruit"],
    ["coconut", "a type of fruit"],
    ["pomegranate", "a type of fruit"],
    ["strawberry", "a type of fruit"],
    ["blueberry", "a type of fruit"],
    ["raspberry", "a type of fruit"],
    ["blackberry", "a type of fruit"],
    ["mango", "a type of fruit"],
    ["pineapple", "a type of fruit"],
    ["peach", "a type of fruit"],
    ["kiwi", "a type of fruit"],
    ["cherry", "a type of fruit"],
    ["avocado", "a type of fruit"],
    ["pear", "a type of fruit"],
    ["plum", "a type of fruit"],
    ["grapes", "a type of fruit"],
    ["coconut", "a type of fruit"],
    ["pomegranate", "a type of fruit"],
    ["strawberry", "a type of fruit"],
    ["blueberry", "a type of fruit"],
    ["raspberry", "a type of fruit"],
    ["blackberry", "a type of fruit"],
    ["mango", "a type of fruit"],
    ["pineapple", "a type of fruit"],
    ["peach", "a type of fruit"],
    ["kiwi", "a type of fruit"],
    ["cherry", "a type of fruit"],
    ["avocado", "a type of fruit"],
    ["pear", "a type of fruit"],
    ["plum", "a type of fruit"],
    ["grapes", "a type of fruit"],
    ["coconut", "a type of fruit"],
    ["pomegranate", "a type of fruit"],
    ["strawberry", "a type of fruit"],
    ["blueberry", "a type of fruit"],
    ["raspberry", "a type of fruit"],
    ["blackberry", "a type of fruit"],
    ["apple", "a sweet fruit"],
    ["dog", "an animal that is often kept as a pet"],
    ["sun", "the big bright thing in the sky"],
    ["house", "a building where people live"],
    ["car", "a vehicle that takes you places"],
    ["phone", "a device that lets you talk to people"],
    ["water", "a liquid that is essential for life"],
    ["cat", "an animal that is often kept as a pet"],
    ["tree", "a tall plant with branches and leaves"],
    ["book", "a collection of pages with writing and pictures"],
    ["paper", "a material used for writing and drawing"],
    ["pen", "a tool used for writing"],
    ["friend", "a person who is close to you"],
    ["family", "the people you live with"],
    ["school", "a place where you learn"],
    ["teacher", "a person who helps you learn"],
    ["food", "something you eat to stay alive"],
    ["music", "a type of sound that is pleasant to listen to"],
    ["play", "to have fun"],
    ["work", "to do a job"],
    ["rest", "to sleep or relax"],
    ["smile", "to show happiness on your face"],
    ["laugh", "to make a happy sound"],
    ["love", "a strong feeling of affection"],
    ["hate", "a strong feeling of dislike"],
    ["run", "to move quickly on your feet"],
    ["jump", "to move quickly up and down"],
    ["stop", "to not move"],
    ["go", "to move from one place to another"],
    ["start", "to begin"],
    ["finish", "to end"],
    ["big", "large"],
    ["small", "not big"],
    ["long", "not short"],
    ["short", "not long"],
    ["hot", "high temperature"],
    ["cold", "low temperature"],
    ["rain", "water falling from the sky"],
    ["snow", "white flakes falling from the sky"],
    ["cloud", "a white or gray mass in the sky"],
    ["sunshine", "the warmth and light of the sun"],
    ["shadow", "a dark shape on the ground"],
    ["light", "not dark"],
    ["dark", "not light"],
    ["day", "the time when the sun is up"],
    ["night", "the time when the sun is down"],
    ["morning", "the time when the sun rises"],
    ["evening", "the time when the sun sets"],
    ["afternoon", "the time between morning and evening"],
    ["week", "a group of seven days"],
    ["month", "a group of days"],
    ["year", "a group of 12 months"]
]



